export const mockUser = {
  id: "user_1",
  name: "John Doe",
  email: "john@example.com",
  isPro: false,
};

export const mockItemTypes = [
  { id: "type_snippet", name: "Snippet", icon: "code", color: "#6366f1", isSystem: true },
  { id: "type_prompt", name: "Prompt", icon: "sparkles", color: "#a855f7", isSystem: true },
  { id: "type_command", name: "Command", icon: "terminal", color: "#22c55e", isSystem: true },
  { id: "type_note", name: "Note", icon: "file-text", color: "#f59e0b", isSystem: true },
  { id: "type_file", name: "File", icon: "paperclip", color: "#64748b", isSystem: true },
  { id: "type_image", name: "Image", icon: "image", color: "#ec4899", isSystem: true },
  { id: "type_url", name: "URL", icon: "link", color: "#0ea5e9", isSystem: true },
];

export const mockCollections = [
  {
    id: "col_1",
    name: "React Patterns",
    description: "Common React patterns and hooks",
    isFavorite: true,
    itemCount: 12,
  },
  {
    id: "col_2",
    name: "Python Snippets",
    description: "Useful Python code snippets",
    isFavorite: false,
    itemCount: 8,
  },
  {
    id: "col_3",
    name: "Context Files",
    description: "AI context files for projects",
    isFavorite: true,
    itemCount: 5,
  },
  {
    id: "col_4",
    name: "Git Commands",
    description: "Frequently used git commands",
    isFavorite: true,
    itemCount: 15,
  },
  {
    id: "col_5",
    name: "Interview Prep",
    description: "Technical interview preparation",
    isFavorite: false,
    itemCount: 24,
  },
  {
    id: "col_6",
    name: "AI Prompts",
    description: "Curated AI prompts for coding",
    isFavorite: false,
    itemCount: 18,
  },
];

export const mockItems = [
  {
    id: "item_1",
    title: "useAuth Hook",
    contentType: "text",
    content: `import { useSession } from 'next-auth/react'\n\nexport function useAuth() {\n  const { data: session, status } = useSession()\n  return { user: session?.user, isLoading: status === 'loading' }\n}`,
    description: "Custom authentication hook for React applications",
    isFavorite: false,
    isPinned: true,
    language: "typescript",
    typeId: "type_snippet",
    collectionId: "col_1",
    tags: ["react", "auth", "hooks"],
    createdAt: "2025-01-15",
  },
  {
    id: "item_2",
    title: "API Error Handling Pattern",
    contentType: "text",
    content: `export async function fetchWithRetry(url: string, retries = 3) {\n  for (let i = 0; i < retries; i++) {\n    try {\n      const res = await fetch(url)\n      if (!res.ok) throw new Error(res.statusText)\n      return await res.json()\n    } catch (e) {\n      if (i === retries - 1) throw e\n    }\n  }\n}`,
    description: "Fetch wrapper with exponential backoff retry logic",
    isFavorite: false,
    isPinned: true,
    language: "typescript",
    typeId: "type_snippet",
    collectionId: "col_1",
    tags: ["typescript", "api", "error-handling"],
    createdAt: "2025-01-12",
  },
  {
    id: "item_3",
    title: "Explain this code",
    contentType: "text",
    content: "You are a senior software engineer. Explain the following code in plain English. Break it down step by step. Point out any potential issues or improvements.",
    description: "General purpose code explanation prompt",
    isFavorite: true,
    isPinned: false,
    language: null,
    typeId: "type_prompt",
    collectionId: "col_6",
    tags: ["ai", "code-review"],
    createdAt: "2025-01-10",
  },
  {
    id: "item_4",
    title: "Git stash with message",
    contentType: "text",
    content: "git stash push -m \"your message here\"",
    description: "Stash changes with a descriptive message",
    isFavorite: false,
    isPinned: false,
    language: "bash",
    typeId: "type_command",
    collectionId: "col_4",
    tags: ["git", "stash"],
    createdAt: "2025-01-08",
  },
  {
    id: "item_5",
    title: "Python list comprehension patterns",
    contentType: "text",
    content: `# Filter and transform\nresult = [x * 2 for x in items if x > 0]\n\n# Nested\nmatrix = [[row[i] for row in matrix] for i in range(len(matrix[0]))]\n\n# Dict comprehension\nsquares = {x: x**2 for x in range(10)}`,
    description: "Common list and dict comprehension patterns",
    isFavorite: false,
    isPinned: false,
    language: "python",
    typeId: "type_snippet",
    collectionId: "col_2",
    tags: ["python", "lists"],
    createdAt: "2025-01-05",
  },
  {
    id: "item_6",
    title: "Project context template",
    contentType: "text",
    content: "You are working on [PROJECT_NAME]. The stack is [STACK]. The current task is [TASK]. Here is the relevant code: [CODE]",
    description: "Reusable project context prompt for AI assistants",
    isFavorite: true,
    isPinned: false,
    language: null,
    typeId: "type_prompt",
    collectionId: "col_6",
    tags: ["ai", "context", "template"],
    createdAt: "2025-01-03",
  },
  {
    id: "item_7",
    title: "DevStash API spec",
    contentType: "file",
    content: null,
    fileUrl: "/files/api-spec.md",
    fileName: "api-spec.md",
    fileSize: 14200,
    description: "Full REST API specification for DevStash",
    isFavorite: false,
    isPinned: false,
    language: null,
    typeId: "type_file",
    collectionId: "col_3",
    tags: ["docs", "api"],
    createdAt: "2024-12-28",
  },
  {
    id: "item_8",
    title: "NextAuth v5 setup notes",
    contentType: "text",
    content: "Remember: callbacks in v5 use `auth()` not `getServerSession()`. Middleware uses `auth` export directly. JWT strategy requires secret in env.",
    description: "Key differences in NextAuth v5 setup",
    isFavorite: false,
    isPinned: false,
    language: null,
    typeId: "type_note",
    collectionId: null,
    tags: ["nextauth", "auth", "next.js"],
    createdAt: "2024-12-20",
  },
  {
    id: "item_9",
    title: "Prisma reset and seed",
    contentType: "text",
    content: "npx prisma migrate reset && npx prisma db seed",
    description: "Reset database and run seed script",
    isFavorite: false,
    isPinned: false,
    language: "bash",
    typeId: "type_command",
    collectionId: "col_4",
    tags: ["prisma", "database"],
    createdAt: "2024-12-18",
  },
  {
    id: "item_10",
    title: "DevStash UI mockup",
    contentType: "file",
    fileUrl: "/files/ui-mockup.png",
    fileName: "ui-mockup.png",
    fileSize: 204800,
    content: null,
    description: "Dashboard UI mockup screenshot",
    isFavorite: false,
    isPinned: false,
    language: null,
    typeId: "type_image",
    collectionId: "col_3",
    tags: ["design", "ui"],
    createdAt: "2024-12-15",
  },
];

export const mockTypeCounts: Record<string, number> = {
  type_snippet: 24,
  type_prompt: 18,
  type_command: 15,
  type_note: 12,
  type_file: 5,
  type_image: 3,
  type_url: 8,
};
